export const money = (value) => `KWD ${Number(value).toFixed(3)}`;

const dictionary = {
  en: {
    chooseLanguage: 'Welcome to Mdawra 👋\nPlease choose your language.',
    languageSet: 'Language set to English.',
    mainMenu: (name) => `Hello ${name || 'there'}! What would you like to do?`,
    browseMenu: 'Browse menu',
    viewCart: 'View cart',
    myLastOrder: 'Last order',
    closed: 'Sorry, we are currently closed. Working hours: {hours}',
    pickCategory: 'Pick a category to see the items.',
    categories: 'Categories',
    pickItem: 'Pick an item to add to your cart.',
    items: 'Items',
    more: 'More…',
    back: 'Back',
    chooseQuantity: (item, price) => `${item} — ${price}\nHow many would you like? Reply with a number (1-20).`,
    invalidQuantity: 'Please reply with a number between 1 and 20.',
    chooseOptions: (group) => `Choose an option for "${group}".`,
    optionsSkip: 'Skip',
    addedToCart: (item, qty) => `Added ${qty} × ${item} to your cart.`,
    cartEmpty: 'Your cart is empty. Send "menu" to start ordering.',
    cartHeader: 'Your cart',
    cartFooter: (subtotal) => `Subtotal: ${subtotal}`,
    addMore: 'Add more',
    checkout: 'Checkout',
    clearCart: 'Clear cart',
    cartCleared: 'Your cart has been cleared.',
    askName: 'What name should we put on the order?',
    askArea: 'Which area are you in? (e.g. Salmiya)',
    askBlock: 'Block number?',
    askStreet: 'Street name/number?',
    askBuilding: 'Building / house number?',
    askExtra: 'Any extra directions or notes for the driver? Reply "no" to skip.',
    useSavedAddress: (address) => `Deliver to your saved address?\n\n${address}`,
    yes: 'Yes',
    newAddress: 'New address',
    choosePayment: 'How would you like to pay?',
    payOnline: 'Pay online',
    payCash: 'Cash on delivery',
    minimumOrder: (min) => `Minimum order value is ${min}. Please add more items.`,
    orderSummary: 'Order summary',
    payNow: (link) => `Tap to pay securely:\n${link}\n\nWe will confirm your order as soon as the payment is received.`,
    paymentUnavailable: 'Online payment is temporarily unavailable. Your order was placed as cash on delivery.',
    orderPlaced: (number, total) =>
      `✅ Order ${number} received!\nTotal: ${total}\nWe will start preparing it right away and keep you posted here.`,
    orderPaid: (number, total) => `💳 Payment received for order ${number} (${total}). Thank you!`,
    paymentFailed: (number) => `We could not confirm the payment for order ${number}. Send "pay" to try again.`,
    statusUpdate: {
      CONFIRMED: (n) => `Order ${n} is confirmed 👍`,
      PREPARING: (n) => `Order ${n} is being prepared 👨‍🍳`,
      READY: (n) => `Order ${n} is ready and on its way 🛵`,
      DELIVERED: (n) => `Order ${n} has been delivered. Enjoy your meal! 🍽️`,
      CANCELLED: (n) => `Order ${n} has been cancelled. Contact us if this was a mistake.`,
    },
    askRating: (number) => `How was order ${number}? Rate us from 1 to 5.`,
    askComment: 'Thanks! Any comments you would like to share? Reply "no" to skip.',
    feedbackThanks: 'Thank you for your feedback 🙏 See you next time!',
    invalidRating: 'Please reply with a number from 1 to 5.',
    fallback: 'Sorry, I did not understand that. Send "menu" to see the options.',
    cancelled: 'No problem, your order was cancelled. Send "menu" to start again.',
    cancel: 'Cancel',
    orderStatus: (number, status) => `Order ${number} — status: ${status}`,
    noOrders: 'You have no previous orders yet.',
  },
  ar: {
    chooseLanguage: 'مرحباً بك في مدورة 👋\nاختر اللغة المفضلة.',
    languageSet: 'تم اختيار اللغة العربية.',
    mainMenu: (name) => `أهلاً ${name || ''}! كيف نقدر نساعدك؟`,
    browseMenu: 'تصفح المنيو',
    viewCart: 'سلة الطلبات',
    myLastOrder: 'آخر طلب',
    closed: 'عذراً، المطعم مغلق حالياً. أوقات العمل: {hours}',
    pickCategory: 'اختر القسم لعرض الأصناف.',
    categories: 'الأقسام',
    pickItem: 'اختر الصنف لإضافته إلى السلة.',
    items: 'الأصناف',
    more: 'المزيد…',
    back: 'رجوع',
    chooseQuantity: (item, price) => `${item} — ${price}\nكم الكمية المطلوبة؟ أرسل رقماً من ١ إلى ٢٠.`,
    invalidQuantity: 'أرسل رقماً بين 1 و 20.',
    chooseOptions: (group) => `اختر من "${group}".`,
    optionsSkip: 'تخطي',
    addedToCart: (item, qty) => `تمت إضافة ${qty} × ${item} إلى السلة.`,
    cartEmpty: 'السلة فارغة. أرسل "منيو" لبدء الطلب.',
    cartHeader: 'سلتك',
    cartFooter: (subtotal) => `المجموع: ${subtotal}`,
    addMore: 'إضافة المزيد',
    checkout: 'إتمام الطلب',
    clearCart: 'إفراغ السلة',
    cartCleared: 'تم إفراغ السلة.',
    askName: 'ما الاسم الذي نسجل به الطلب؟',
    askArea: 'في أي منطقة أنت؟ (مثال: السالمية)',
    askBlock: 'رقم القطعة؟',
    askStreet: 'اسم أو رقم الشارع؟',
    askBuilding: 'رقم المنزل / البناية؟',
    askExtra: 'أي تفاصيل إضافية للمندوب؟ أرسل "لا" للتخطي.',
    useSavedAddress: (address) => `نوصل الطلب إلى عنوانك المحفوظ؟\n\n${address}`,
    yes: 'نعم',
    newAddress: 'عنوان جديد',
    choosePayment: 'كيف تحب تدفع؟',
    payOnline: 'دفع إلكتروني',
    payCash: 'نقداً عند التسليم',
    minimumOrder: (min) => `الحد الأدنى للطلب ${min}. أضف المزيد من الأصناف.`,
    orderSummary: 'ملخص الطلب',
    payNow: (link) => `اضغط للدفع بشكل آمن:\n${link}\n\nسنؤكد طلبك بعد استلام الدفعة.`,
    paymentUnavailable: 'الدفع الإلكتروني غير متاح حالياً، تم تسجيل طلبك كدفع نقدي عند التسليم.',
    orderPlaced: (number, total) =>
      `✅ تم استلام طلبك ${number}!\nالإجمالي: ${total}\nسنبدأ التحضير فوراً وسنبقيك على اطلاع هنا.`,
    orderPaid: (number, total) => `💳 تم استلام الدفعة للطلب ${number} (${total}). شكراً لك!`,
    paymentFailed: (number) => `لم نتمكن من تأكيد الدفع للطلب ${number}. أرسل "دفع" للمحاولة مرة أخرى.`,
    statusUpdate: {
      CONFIRMED: (n) => `تم تأكيد الطلب ${n} 👍`,
      PREPARING: (n) => `جاري تحضير الطلب ${n} 👨‍🍳`,
      READY: (n) => `الطلب ${n} جاهز وفي الطريق إليك 🛵`,
      DELIVERED: (n) => `تم توصيل الطلب ${n}. بالهناء والشفاء! 🍽️`,
      CANCELLED: (n) => `تم إلغاء الطلب ${n}. تواصل معنا إذا كان ذلك بالخطأ.`,
    },
    askRating: (number) => `كيف كانت تجربتك مع الطلب ${number}؟ قيمنا من 1 إلى 5.`,
    askComment: 'شكراً! هل لديك أي ملاحظات؟ أرسل "لا" للتخطي.',
    feedbackThanks: 'شكراً لملاحظاتك 🙏 نراك قريباً!',
    invalidRating: 'أرسل رقماً من 1 إلى 5.',
    fallback: 'عذراً، لم أفهم ذلك. أرسل "منيو" لعرض الخيارات.',
    cancelled: 'تم إلغاء الطلب. أرسل "منيو" للبدء من جديد.',
    cancel: 'إلغاء',
    orderStatus: (number, status) => `الطلب ${number} — الحالة: ${status}`,
    noOrders: 'لا توجد طلبات سابقة.',
  },
};

export const t = (lang) => dictionary[lang === 'ar' ? 'ar' : 'en'];

export const itemName = (lang, item) => (lang === 'ar' && item.nameAr ? item.nameAr : item.nameEn);

export const categoryName = (lang, category) => (lang === 'ar' ? category.nameAr : category.nameEn);
